In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("HCAHPS-National.csv")
df.head()

,HCAHPS Measure ID,HCAHPS Question,HCAHPS Answer Description,HCAHPS Answer Percent,Footnote,Start Date,End Date
0,H_COMP_1_A_P,"Patients who reported that their nurses ""Alway...","Nurses ""always"" communicated well",80,NaN,01/01/2024,12/31/2024
1,H_COMP_1_SN_P,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" communicated well",4,NaN,01/01/2024,12/31/2024
2,H_COMP_1_U_P,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" communicated well",16,NaN,01/01/2024,12/31/2024
3,H_NURSE_RESPECT_A_P,"Patients who reported that their nurses ""Alway...","Nurses ""always"" treated them with courtesy and...",87,NaN,01/01/2024,12/31/2024
4,H_NURSE_RESPECT_SN_P,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" treated them wit...",3,NaN,01/01/2024,12/31/2024

In [29]:
df.shape

(72, 7)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   HCAHPS Measure ID          72 non-null     object
 1   HCAHPS Question            72 non-null     object
 2   HCAHPS Answer Description  72 non-null     object
 3   HCAHPS Answer Percent      72 non-null     int64
 4   Footnote                   0 non-null      float64
 5   Start Date                 72 non-null     object
 6   End Date                   72 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 4.1+ KB

In [31]:
df.describe()

       HCAHPS Answer Percent  Footnote
count              72.000000       0.0
mean               34.722222       NaN
std                29.027050       NaN
min                 3.000000       NaN
25%                 9.000000       NaN
50%                20.500000       NaN
75%                62.750000       NaN
max                88.000000       NaN

In [32]:
df.columns = df.columns.str.lower().str.replace(" ", "_") #modifying column names to improve data standards

df['start_date'] = pd.to_datetime(df['start_date'])
df['end_date'] = pd.to_datetime(df['end_date'])

df.isnull().sum()

hcahps_measure_id             0
hcahps_question               0
hcahps_answer_description     0
hcahps_answer_percent         0
footnote                     72
start_date                    0
end_date                      0
dtype: int64

In [33]:
response_distribution = (                                #grouping responses in a separate dataframe for analysis
    df.groupby('hcahps_answer_description')['hcahps_answer_percent']
    .mean()
    .sort_values(ascending=False)
)

response_distribution

hcahps_answer_description
Yes, staff "did" give patients information about possible symptoms                                              88.0
Nurses "always" treated them with courtesy and  respect                                                         87.0
Yes, staff "did" give patients this information                                                                 87.0
Doctors "always" treated them with courtesy and  respect                                                        86.0
Yes, staff "did" give patients information about help after discharge                                           85.0
                                                                                                                ...
Patients who "Disagree" or "Strongly Disagree" they understood their medications when they left the hospital     5.0
Nurses "sometimes" or "never" communicated well                                                                  4.0
Nurses "sometimes" or "never" listened carefully                                                                 4.0
Nurses "sometimes" or "never" treated them with courtesy and  respect                                            3.0
Doctors "sometimes" or "never" treated them with courtesy and  respect                                           3.0
Name: hcahps_answer_percent, Length: 72, dtype: float64

In [34]:
communication_df = df[      #creating a dataFrame that contains only questions related to nurse or doctor communication
    df['hcahps_question'].str.contains("nurse|doctor", case=False)
]

communication_df[['hcahps_question', 'hcahps_answer_description', 'hcahps_answer_percent']]

,hcahps_question,hcahps_answer_description,hcahps_answer_percent
0,"Patients who reported that their nurses ""Alway...","Nurses ""always"" communicated well",80
1,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" communicated well",4
2,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" communicated well",16
3,"Patients who reported that their nurses ""Alway...","Nurses ""always"" treated them with courtesy and...",87
4,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" treated them wit...",3
5,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" treated them with courtesy a...",10
6,"Patients who reported that their nurses ""Alway...","Nurses ""always"" listened carefully",78
7,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" listened carefully",4
8,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" listened carefully",18
9,"Patients who reported that their nurses ""Alway...","Nurses ""always"" explained things so they could...",76
10,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" explained things...",5
11,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" explained things so they coul...",19
12,"Patients who reported that their doctors ""Alwa...","Doctors ""always"" communicated well",80
13,"Patients who reported that their doctors ""Some...","Doctors ""sometimes"" or ""never"" communicated well",5
14,"Patients who reported that their doctors ""Usua...","Doctors ""usually"" communicated well",15
15,"Patients who reported that their doctors ""Alwa...","Doctors ""always"" treated them with courtesy an...",86
16,"Patients who reported that their doctors ""Some...","Doctors ""sometimes"" or ""never"" treated them wi...",3
17,"Patients who reported that their doctors ""Usua...","Doctors ""usually"" treated them with courtesy ...",11
18,"Patients who reported that their doctors ""Alwa...","Doctors ""always"" listened carefully",79
19,"Patients who reported that their doctors ""Some...","Doctors ""sometimes"" or ""never"" listened carefully",5
20,"Patients who reported that their doctors ""Usua...","Doctors ""usually"" listened carefully",16
21,"Patients who reported that their doctors ""Alwa...","Doctors ""always"" explained things so they coul...",75
22,"Patients who reported that their doctors ""Some...","Doctors ""sometimes"" or ""never"" explained thing...",6
23,"Patients who reported that their doctors ""Usua...","Doctors ""usually"" explained things so they cou...",19

In [35]:
top_metrics = df.sort_values('hcahps_answer_percent', ascending=False).head(10) # sorting postive responses in a descending order
bottom_metrics = df.sort_values('hcahps_answer_percent').head(10) #sorting negative responses in a descending order

top_metrics[['hcahps_question', 'hcahps_answer_percent']]

                                      hcahps_question  hcahps_answer_percent
47  Patients who reported that YES, they did recei...                     88
3   Patients who reported that their nurses "Alway...                     87
43  Patients who reported that YES, they were give...                     87
15  Patients who reported that their doctors "Alwa...                     86
45  Patients who reported that YES, they did discu...                     85
0   Patients who reported that their nurses "Alway...                     80
12  Patients who reported that their doctors "Alwa...                     80
18  Patients who reported that their doctors "Alwa...                     79
6   Patients who reported that their nurses "Alway...                     78
9   Patients who reported that their nurses "Alway...                     76

In [36]:
bottom_metrics[['hcahps_question', 'hcahps_answer_percent']]

                                      hcahps_question  hcahps_answer_percent
4   Patients who reported that their nurses "Somet...                      3
16  Patients who reported that their doctors "Some...                      3
7   Patients who reported that their nurses "Somet...                      4
1   Patients who reported that their nurses "Somet...                      4
13  Patients who reported that their doctors "Some...                      5
10  Patients who reported that their nurses "Somet...                      5
19  Patients who reported that their doctors "Some...                      5
58  Patients who "Disagree" or "Strongly Disagree"...                      5
55  Patients who "Disagree" or "Strongly Disagree"...                      5
69  Patients who reported NO, they would probably ...                      5

In [44]:
strengths = (
    df[df['hcahps_answer_description'].str.contains("Always|Yes", case=False)]
    .sort_values('hcahps_answer_percent', ascending=False)
    .head(5)
)
                                             #sorting strengths and improvements needed
improvements = (
    df[df['hcahps_answer_description'].str.contains("Never|Sometimes|No", case=False)]
    .sort_values('hcahps_answer_percent', ascending=False)
    .head(5)
)

strengths[['hcahps_question', 'hcahps_answer_percent']]

                                      hcahps_question  hcahps_answer_percent
47  Patients who reported that YES, they did recei...                     88
43  Patients who reported that YES, they were give...                     87
3   Patients who reported that their nurses "Alway...                     87
15  Patients who reported that their doctors "Alwa...                     86
45  Patients who reported that YES, they did discu...                     85

In [47]:
improvements[['hcahps_question', 'hcahps_answer_percent']]

                                      hcahps_question  hcahps_answer_percent
40  Patients who reported that when receiving new ...                     29
34  Patients who reported that staff "Sometimes" o...                     19
44  Patients who reported that NO, they did not di...                     15
42  Patients who reported that NO, they were not g...                     13
46  Patients who reported that NO, they did not re...                     12

In [48]:
# The End